packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  workerd: true

minimumReleaseAgeExclude:
  - '@prisma/composer-cli@0.23.0'
  - '@prisma/composer@0.23.0'
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - dotenv@18.0.4
  - prisma@8.0.0-rc.17
  - turbo@2.11.4
